@URL=http://localhost:3001/users
################ GET ################
### Obter todos
GET {{URL}}

### Obter pelo ID
GET {{URL}}/651d9c37780d5c66e


################ POST ###############
### Inserir novo usuario
POST {{URL}}/
Content-Type: application/json

{
    "email": "fulano@gmail.com",
    "password": "123456",
    "phone": "123456789"
}

################ PUT ################
### Alterar um usuario
PUT {{URL}}/651d9c37d1370ce780d5c66e
Content-Type: application/json

{
    "name": "Fuaaalano",
    "password": "123456",
    "phone": "123456789"
}

############### DELETE ##############
### Deletar um usuario
DELETE {{URL}}/651dab4c65d15d3278633e38
